# Base Units
TILE_LENGTH = 8

# App Dimensions
APP_NUM_ROWS = 48
APP_NUM_COLS = 64

APP_WIDTH = TILE_LENGTH * APP_NUM_COLS
APP_HEIGHT = TILE_LENGTH * APP_NUM_ROWS

# Widget Dimensions
ENTRY_ROWS = 5
ENTRY_COLS = 39
ENTRY_WIDTH = TILE_LENGTH * ENTRY_COLS
ENTRY_HEIGHT = TILE_LENGTH * ENTRY_ROWS

COMBOBOX_ROWS = 5
COMBOBOX_COLS = 23
COMBOBOX_WIDTH = TILE_LENGTH * COMBOBOX_COLS
COMBOBOX_HEIGHT = TILE_LENGTH * COMBOBOX_ROWS

BUTTON_ROWS = 5
BUTTON_COLS = 31
BUTTON_WIDTH = TILE_LENGTH * BUTTON_COLS
BUTTON_HEIGHT = TILE_LENGTH * BUTTON_ROWS

# Expenses
EXPENSE_TYPES = ['cheetos', 'fart porn']
CURRENCIES = ['IDR', 'THB', 'USD', 'VND']

# Fonts
DATE_ENTRY_FONT = ("Roboto", 16)
