# Measurements
TILE_LENGTH = 8

# App Dimensions
APP_NUM_CELLS = 8

APP_NUM_TILE_IN_ROWS = 6
APP_NUM_TILE_IN_COLS = 8

APP_CELL_WIDTH = TILE_LENGTH * APP_NUM_CELLS
APP_CELL_HEIGHT = TILE_LENGTH * APP_NUM_CELLS

APP_WIDTH = APP_CELL_WIDTH * APP_NUM_TILE_IN_COLS
APP_HEIGHT = APP_CELL_HEIGHT * APP_NUM_TILE_IN_ROWS

# Expenses

EXPENSE_TYPES = ['cheetos', 'fart porn']
